name: MacOS.Collection.hosts
description: |
  /etc/hosts on macOS to check host file and upload the file contents.
author: Ali Jammal

precondition: SELECT OS FROM info() WHERE OS =~ 'darwin'

parameters:
- name: hostsglob
  default: /etc/hosts

sources:
- name: Hosts files
  query: |
    SELECT OSPath, Name, Mtime, Size,
           hash(path=OSPath) AS SHA256,
           upload(file=OSPath) AS Upload
    FROM glob(globs=split(string=hostsglob, sep=","))
